### ISSUE TITLE
The Volume 1 page is too long

### ISSUE THREAD

**Issue by DavidPyke** [IHE/ITI.MHDS#3]
Volume 1 is too long and the length will make the finding of text difficult as there is no index or other way of breaking it up for ease of use.   I would suggest breaking it into 6 pages (one per 50.x subsection) with an index to make finding the information easier.

**Comment by JohnMoehrke** [comment]
Committee looked at this today and feel that the size is not an issue, and that a single page is workable with the menu breakdown, and the table of content on the right. Further search-on-page is more useful.
